name: Generate SBOM
on: [push]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-action-generate-sbom@v1
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom.json
          path: bom.json
