name: Generate SBOM
on: [push]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install dependencies
        run: npm install  

      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-action-generate-sbom@v1
        with:
          project-type: node  

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom.json
          path: bom.json  